export const Users = [
    {
        "id" : 1,
        "quote" : "There was high uncertainty of not getting selected...",
        "name" : "Abhishek Kabi",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "P&G (Supply Chain)",
        "mentalProblem" : "There was high uncertainty of not getting selected by any company, and I was stressed because it was difficult for me to do coding, as it was uninteresting.",
        "mentalSolution": "I started telling myself that CDC is not the end of the journey, and there can be many other ways to get internship.",
        "careerProblem" : "My biggest query was whether I need to put efforts on learning to code or focus on non-tech roles.",
        "careerSolution" : "I realised that while learning to code was a safe and competitive option, but I was definitely not interested in doing it.",
        "roadmap" : "I focused on building my profile around Consult and Supply Chain, learnt about the companies and then individually checked their selection process",
        "resources" : "I relied upon the case study videos on youtube and interview videos of seniors.",
        "message" : "I would suggest you to trust yourself. CDC is not the end, and you have a long way to go.",
        "tags" : "consulting fmcg core strategy on-campus campus 180DC 180 degree dc supply chain industrial"
    },

    {
        "id" : 2,
        "quote" : "I changed my profile a month before CDC...",
        "name" : "Binay Bhattacharya",
        "mode" : "Off-campus",
        "college" : "IIT Kharagpur",
        "company" : "Venwiz (Strategy)",
        "mentalProblem" : "I was trapped in the FOMO of CDC and sometimes got into panic attacks. Things seemed to be uncertain during the summer vacation. Seeing my friends working hard behind it, I became more nervous. Even after my internship was sorted off-campus, I used to feel uneasy seeing students cracking big companies.",
        "mentalSolution": "I used to spend time alone in the roof of my hall, and listened to music. That was accompanied with self-talk and affirmations that things will be okay soon, and I will become stronger." ,
        "careerProblem" : "During my summers, I was in a dilemma of which career path to choose. I had learnt web development for internships, and gave coding contests which fetched me good ranks. But as the CDC season arrived, I started losing confidence and my rank started decreasing. I had then started considering strategy and consulting roles.",
        "careerSolution" : "I took some time to think about a career change, but once I was determined, I did not look back. I did a few internships in strategy role and started building my new profile. I changed my path from CDC to off-campus, and ultimately sorted out my upcoming summers in a great company with a good package.",
        "roadmap" : "I tested my coding skills for sometime until I realized that strategy and consulting is a better role for me. I learnt the basics of the career path and started doing off-campus internships. I ultimately got my summer internship offer for a strategy role.",
        "resources" : "Consulting course of Guwahati, Youtube lectures and case analysis of Victor Cheng and mock interview videos were some important resources I followed.",
        "message" : "You have the potential to do anything, but not everything. Figure out what you are actually made for, and once you have made the decision, don't look back again. Every path, wide or narrow, if followed whole-heartedly, will lead you to something miraculous.",
        "tags" : "consulting non-core chemical engineering strategy entrepreneurship startup music singing"
    },
    
    {
        "id" : 3,
        "quote" : "I worked hard for days and nights, but did not get shortlisted...",
        "name" : "Ujjwal Raj",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Simpl (SDE)",
        "mentalProblem" : "In summers I worked very hard to learn to code and CP and all. I spent days and nights, and solved hundred of problems. Despite all those, I couldn't see my name shortlisted in any company for days. I started believing that I am not fit for the profile or competition in KGP. Self Doubt on my capabilities started growing inside me. People with malpractices got selected- I used to feel very sad when non-deserving candidates doing malpractice got selected.",
        "mentalSolution": "I kept on solving problems and tried to keep myself occupied all the time. I kept convincing myself that even if I don't get selected I will do a project during my summers. I persuaded myself to keep on coding so that after 1 year (in placements) I will be an awesome coder. I always used to keep myself occupied and motivated that placement is there to help me out anyways. I kept myself busy doing others things like learning new skills, applying off-campus to all job posts in all firms and LinkedIn.",
        "careerProblem" : "I didn't know that there is so much competition in KGP. To be honest, everyone is coding in KGP and this increases the competition. Months before CDC, I didn't do anything else other than CP. I also rejected some internship offers and other activities so that I could prepare well for CDC during my semester and summers as well. But this was not at all necessary. Extra activities and intern would have helped me build my resume better. I would have rather mastered the art of time management than running away from them.",
        "careerSolution" : "I applied in a lot of off-campus job portals, linkedin, and what not. I recreated my cv, gave contests to increase my ratings, and added interesting project in my resume. The best thing I did was that I kept on solving problems everyday. My friends who got the offers used to motivate me to keep doing CP and that helped me a lot keeping me busy during the go.",
        "roadmap" : "During the semester before CDC, I did moderate CP and participated in tech hackathons(Tech GC if in kgp). Added to that, I did a good self project and searched for summer internship under any prof or in a startup. \n During summers, I did hardcore coding (5-6 hrs daily) If you are doing an internship during this phase, learn to manage your time properly.\n During the CDC internship drive, I solved the PYQs of companies, SDE sheet and did revision.",
        "resources" : "The main resources I used were Algozenith, InterviewBit for company-wise PYQs, and GeeksForGeeks (GFG) for regular practice during the drive.",
        "message" : "Keep going. Aim high but always be prepared for any circumstance. CDC is not everything. Placement is there for you anyways.",
        "tags" : "sde software mechanical coding cp dsa competitive programming"
    },
    
    {
        "id" : 4,
        "quote" : "It was haunting to get rejected after interviews on Day-1...",
        "name" : "Shah Dhruv Rajendrabhai",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Jaguar (SDE)",
        "mentalProblem" : "One of the most haunting things I experienced in my life was Day 1 of CDC where I was rejected by two companies in which I was shortlisted in Day 1. I was not able to crack the interviews. I was good in the first interview but the question they gave was to be solved in a more efficient way than I did. Due to it I was rejected. The  next went bad because my confidence was dead due to the first. But this shouldn't happen.",
        "mentalSolution": "I talked to my parents as they are my support system. They cheered me up and motivated me for Day 2. I shared with them the whole interview thing, and they just said 'Be confident with your body language and emotions', and their advice worked. I cracked JLR on Day 2. Also I'm a Bhakt of God so I listened some Bhakti songs and read Sunderkaand once. You should be motivated even after the rejections.",
        "careerProblem" : "In my preparation, there were no problems. However, on my first interview od Day 1, a question was to be solved in th best of O(1) time complexity, while I solved in O(log n) and got rejected.",
        "careerSolution" : " Try to give the best answer in interview and get some hints from the interviewer. Along with that, revise your concepts before the interview, and look confident during the interview.",
        "roadmap" : "I just kept doing CP with proper concentration. You shouldn't focus on many things and end up losing everything but should focus on one particular thing at a time.",
        "resources" : "For CP, I did Algozenith and gave contests on CodeForces.",
        "message" : "Trust on yourself and God, and share your problems with your parents (or someone who you trust) as they have seen life more than you and their solutions might work well. Everyone faces tough times, but the one who stays motivated wins the game. ",
        "tags" : "sde software cse computer science coding cp dsa competitive programming"
    },

    {
        "id" : 5,
        "quote" : "I did not have a clear idea of what I wanted to pursue...",
        "name" : "Suman Das",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "ITC (Supply Chain)",
        "mentalProblem" : "It was really mentally draining, specially while applying and checking the CDC mails all the time. And also during the selection process these was a lot of uncertainty regarding whether I made it to the next round. Mentally it was tiring and depressing sometimes.",
        "mentalSolution": "When I got the offer all the anxiety subsided eventually. During the process, talking to seniors and friends helped me gain confidence and guidance on how to go about things. Personally, I kept my expectations as low as possible so that later I wouldn't be disheartened. I realized that I just need to give my best. What happens after that really doesn't matter. It is all cause and effect.",
        "careerProblem" : "Career confusion definitely bugged me a lot. Specifically not knowing the opportunities and lifestyle I would lead after choosing a particular career path. Seniors are always there to help and give guidance, so approaching them would be a very good choice.",
        "careerSolution" : "Talking to my batchmates was the most beneficial thing that I did which helped me get a clear picture of what I really wanted to do and the companies I would like to apply for. I also thought about the life I want to lead and the things I want to do later in life and which career path would better help me pursue those. Finally after I got the offer I was happy that I would get an opportunity to rock in the domain of my choice.",
        "roadmap" : "I was into core Mechanical Engineering and did a few projects which helped me a lot to bag the internship. Also I studied my core subjects well which helped me clear the technical round. The GD round was all about clarity of thought and presence of mind which fortunately i did well in.",
        "resources" : "I read blogs of seniors and talked to them which helped me. Also my class notes were beneficial ",
        "message" : "Just keep calm and go ahead. Something great is waiting for you. Be clear about what you want to do and how you can reach your dreams and goals. ",
        "tags" : "supply chain fmcg core mechanical tfps"
    },

    {
        "id" : 6,
        "quote" : "I recall how hard our parents are working so that we lead a comfortable life...",
        "name" : "Sayan Layek",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Jaguar (SDE)",
        "mentalProblem" : "When there was a stop in skill growth, I started getting frustrated. This frustration further induced low confidence, and thus, I was then unable to solve easier questions as well.",
        "mentalSolution": "When I get frustrated or depressed, I recall how hard my parents are working to keep me in the race so that I can lead a comfortable life in the future, and I should not let them down.",
        "careerProblem" : "I was not able to improve my coding skills in the summer before Internships. At the same time, I was doing a project under a professor. So, I faced time management issues as well.",
        "careerSolution" : "When I was unable to solve the coding questions of a particular level, I practiced a lot of questions of that level. This is how I improved my coding skills. Talking about the project, I talked to my professor to provide me some time to focus on my CDC journey. So, you often need to clearly speak out your opinion.",
        "roadmap" : "I focused on DSA and coding contests to constantly improve myself. Before the interview, I talked to my mentor and grilled upon my CV and the important keywords used.",
        "resources" : "Codechef and Codeforces for practicing, and hackerrank & Leetcode towards the end helped me a lot.",
        "message" : "There is a beautiful quote by Helen Keller, 'No pessimist ever discovered the secret of the stars, or sailed an uncharted land or opened a new doorway for the human spirit.' So, I believe it is important to stay optimistic in whatever you are doing, because the opposite won't fetch you results anyways. ",
        "tags" : "sde software mechanical engineering coding cp dsa competitive programming"
    },

    {
        "id" : 7,
        "quote" : "I stopped worrying about the WHAT IF's and focused on HOW TO...",
        "name" : "Pushparaj Singh",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Amazon (SDE)",
        "mentalProblem" : "I didn't face any significant mental health issues. Talking precisely, I did not get into any significant FOMO or peer pressure.",
        "mentalSolution": "I believe on the thought, 'If it happens, well and good. However, if it does not happen, will see'. And this keeps me stress-free.",
        "careerProblem" : "I faced conceptual problems in DSA, for topics like graphs. It was difficult for me at the first glance to solve these questions.",
        "careerSolution" : "I gave it time, and just kept practising questions. Ultimately i was able to understand the flow of the concept.",
        "roadmap" : "I started preparing around April-May for the internship drive. Your dept CGPA is important when considered SDE. POR and Projects were not that valuable for this role.",
        "resources" : "GFG practice worked the best as a resource for me.",
        "message" : "Luck often plays a significant role in your life events. It may be in favour or against you. Don't take things too seriously. ",
        "tags" : "sde software non-core chemical engineering coding cp dsa competitive programming"
    },

    {
        "id" : 8,
        "quote" : "If you know DSA, then cracking the first few tests will be easier for you...",
        "name" : "Vedant Gulve",
        "mode" : "MITACS",
        "college" : "IIT Kharagpur",
        "company" : "University of Calgary (ML)",
        "mentalProblem" : "I was highly uncertain about which university I would get, and that confusion made me feel low at times.",
        "mentalSolution": "I talked to the closed ones at my home, and they motivated me to stress less, and explore the opportunities available in front of me.",
        "careerProblem" : "Just like anyone else, I was initially confused about what to pursue in my career. I ultimately continued with machine learning.",
        "careerSolution" : "I searched for some good foreign university projects and learnt a lot of skills by working on them. I got a confidence boost when I was finally selected.",
        "roadmap" : "I began with ML and data and started building my skills. Then I got a project off-campus that helped me brush up my skills and explore new dimensions of machine learning. Finally I got an offer through MITACS.",
        "resources" : "Coursera ML courses and Andrew NG courses on youtube proved to be a great resource for me.",
        "message" : "If you are willing to get into technical profile, then I would advise you to learn and practice DSA (data structure and algorithm), so that it is not difficult for you to crack the coding tests.",
        "tags" : "ml machine learning data science analytics electronics electrical engineering non-core"
    },

    {
        "id" : 9,
        "quote" : "I started my preparation for internships quite late...",
        "name" : "Suhas AM",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Jio (SDE)",
        "mentalProblem" : "I had started my preparation for the CDC internships so late, and was worried about what would happen now. Everyone else around me was much more prepared.",
        "mentalSolution": "What helped me to come out of my low self-esteem  was to practically face the coding tests and interviews.",
        "careerProblem" : "I was lacking in my preparation and that also reflected in my interviews. It was difficult for me to solve the coding questions that could have been easily solved given that I had a better preparation by starting earlier.",
        "careerSolution" : "I faced the tests and interviews and observed the kind of questions being ask3ed. Accordingly, I continued with my preparation, leaving no stones unturned in the remaining time.",
        "roadmap" : "I started my internship preparation in the last half of the month of July. I did not appear for any competitive coding contests. I practised a lot of questions of the main topics of DSA.",
        "resources" : "The main resources used by me were Leetcode, Codechef, and youtube videos.",
        "message" : "Keep yourself updated with the process. Contact your seniors to know their experiences.",
        "tags" : "sde software computer science engineering cse coding cp dsa competitive programming"
    },

    {
        "id" : 10,
        "quote" : "Being from non-circuital branch, I was worried about the competition...",
        "name" : "Anushka Chatterjee",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Nomura (Finance)",
        "mentalProblem" : "Belonging to a non-circuital department, I was always worried that maximum of the companies won't open for me or even if they do they won't prefer us over circuital department students. The competition is pretty high in IIT Kharagpur. All these things made me worried about getting an internship during CDC.",
        "mentalSolution": "I talked with my seniors and communicated to them about my issues. All of them were very helpful and comforting and guided me on how I need to prepare myself so that I can get an internship. They shared with me their stories about how their condition was not very different from mine and still they managed yo do well. This motivated me to try harder.",
        "careerProblem" : "My coding skills weren't very good and most of the companies took CP tests for their selection. The competition in IIT Kharagpur is anyways too high. All these things made me worried about getting an internship during CDC.",
        "careerSolution" : "I took the guidance of my seniors to understand the kind of questions they faced during their interviews. I prepared myself accordingly.",
        "roadmap" : "I had already done 2-3 internships (mainly in ML/AI domain) by the end of my 2nd year and had started practising CP (covering it's topics). However, I mainly did my preparation in the summer holidays. First I completed learning all the important CP topics and kept giving tests in the coding platforms to get a time bound practice. Next I brushed my probability and statistics concepts and practised questions on that as well. In the last month I went through puzzles, case studies, ML concepts.",
        "resources" : "For Cp, I used Algozenith, leetcode and InterviewBit. I covered my Probability and Statistics from Stats 110 by Harvard University. Other than that, I revised my older concepts of Machine Learning.",
        "message" : "Be confident during tests and interviews. Do not get frustrated or carried away looking at other people. Everyone has a separate journey. Keep trying till the end.  Many companies come and it is a very long process. Being persistent and not giving up is the key. All the best!",
        "tags" : "chemical engineering finance non-tech non-core"
    },

    {
        "id" : 11,
        "quote" : "I was trying to focus on multiple profiles and lacked focus...",
        "name" : "Aryan Gupta",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Amazon (SDE)",
        "mentalProblem" : "The main problem that I faced would be the anxiety of performance and peer pressure. You feel a constant need to perform and for obvious reasons, it's hard to find guidance for nuisances when everyone is trying to sort out themselves.",
        "mentalSolution": "My main focus was being self evaluative, understanding the situation and the scenario that I was facing. It was important to acknowledge that certain outcomes, negative or positive, were beyond control and there was no reason to worry about them.",
        "careerProblem" : "I had my focus in technology driven domains. But didn't specifically focus on Software, Data or Machine Learning. This diverted my focus due to the variety I was trying to cover to improve my chances.",
        "careerSolution" : "I didn't take any active decisions in this regard. I wanted to maximize my chances by trying it all out given the luck factor in the process.",
        "roadmap" : "I had a clear mindset that I wished to tread into the software development domain and build core utilities that actually create impact. So I did many projects to learn the workflow involved(My interest in IOT was a bonus). Data Structures and Algorithms were necessary to go ahead.",
        "resources" : "YouTube was the biggest helper.(Documents compiled by seniors are good guidance for resources.)",
        "message" : "Try to keep calm and stay focused and there is a lot of life left ahead so it is only a plus to achieve something at this early a stage. This process is good enough to give you a jolt of action so that you take steps to become industry-ready. Try learning stuff that you think is gonna be a game changer and necessity for the future.",
        "tags" : "sde software chemical engineering coding cp dsa competitive programming"
    },

    {
        "id" : 12,
        "quote" : "I was trying to focus on multiple profiles and lacked focus...",
        "name" : "Yash Jangade",
        "mode" : "CDC",
        "college" : "IIT Kharagpur",
        "company" : "Dr. Reddy (Core)",
        "mentalProblem" : "During CDC, there is always a huge peer pressure as your friends would get internship offers before you, etc. Also, as we were notified about the interviews before 7-8 hours, there was always a sense of unpreparedness which just made me feel tensed and nervous. The CDC process was dynamic and would test your emotional strength.",
        "mentalSolution": "The best solution for this for me was to talk with friends. They had a solution for every problem. Also, before interview if I felt tensed, I practiced some breathing exercise to calm down.",
        "careerProblem" : "It was difficult to decide which career path was best for me. Also, there was no proper roadmap for preparation. ",
        "careerSolution" : "I consulted with many seniors and they helped me find the most suitable career for me as per my skills.",
        "roadmap" : "I was focused on 3 careers: FMCG, core and product profile. I prepared for them simultaneously and got placed in a chemical core company.",
        "resources" : "I followed 'swipe to unlock', 'How to crack PM interviews' and 'decode and conquer' for product profile. For FMCG, I used 'Basic Supply chain Management'. Finally for my core, I used the course material of Chemical Engineering.",
        "message" : "If you are sitting for CDC, don't just prepare the subject matter, prepare yourselves to sustain the huge pressure which you face during the process. Keep in touch with the seniors as they will guide you and talk with friends about your problem, they will help you tackle that problem. Rest you can study for the test and interviews by yourselves. All the Best!!! :)",
        "tags" : "core chemical engineering product fmcg non-technical"
    }
]